name: Run tests

on:
  push:

jobs:
  python-test:
    runs-on: ubuntu-latest
    name: py3.11
    steps:
      - uses: actions/checkout@v3

      - name: Install AppMap tools
        uses: getappmap/install-action@v1
        with:
          install-appmap-library: false
          tools-url: https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-context-api.f9e7755f/appmap-linux-x64

      - name: Docker build :code
        run: docker build -f Dockerfile.codechallenge.code -t sqlfluff:code .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install tox

      - name: Parse Python Version
        id: py_version
        run: |
          PYVERSION=$(echo "3.11" | sed -e 's/\.//g')
          echo "PYVERSION=$PYVERSION" >> $GITHUB_OUTPUT

      - name: Run the tests (without coverage)
        # There are a few failures, disable them.
        run: tox -e py3.11 -- -n 2 test -m "not integration" --durations=16 || true

      - name: Collect and index AppMaps
        run: |
          mkdir -p tmp && mv target/appmap tmp/
          # Index the AppMap data, creating index directories.
          appmap index
          # Build source and AppMap data index files.
          appmap context-provider --no-listen

      - name: Docker build :web
        run: |
          cp -r /usr/local/bin/appmap .
          env DOCKER_BUILDKIT=0 docker build -f Dockerfile.codechallenge -t sqlfluff:web --pull=false .
